# This file contains all available configuration options
# with their default values.
version: "2"
run:
  # Timeout for analysis, e.g. 30s, 5m.
  timeout: 5m
  allow-parallel-runners: true

output:
  show-stats: true

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - blank
        - dot
        - alias
        - localmodule
    gofmt:
      simplify: true
      rewrite-rules:
        - pattern: "interface{}"
          replacement: "any"
    gofumpt:
      extra-rules: true
    golines:
      reformat-tags: false
      max-len: 120

linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - contextcheck
    - depguard
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - forcetypeassert
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - godoclint
    - godot
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - iface
    - importas
    - inamedparam
    - ineffassign
    - intrange
    - iotamixing
    # - ireturn
    - makezero
    - mirror
    - misspell
    - modernize
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - noinlineerr
    # - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - recvcheck
    - revive
    - sloglint
    - staticcheck
    - tagalign
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - wrapcheck
    - wsl_v5

  settings:
    misspell:
      locale: US
      mode: default

    exhaustive:
      default-signifies-exhaustive: true

    wsl_v5:
      allow-whole-block: true
      case-max-lines: 2
      default: all
      disable:
        - assign-exclusive
        - if

    unused:
      field-writes-are-uses: false
      exported-fields-are-used: false
      local-variables-are-used: false

    govet:
      enable-all: true
      disable:
        - shadow

    usetesting:
      os-temp-dir: true
      context-background: true
      context-todo: true

    testifylint:
      enable-all: true
      expected-actual:
        pattern: ^want

    sloglint:
      attr-only: true
      static-msg: true
      args-on-sep-lines: true
      key-naming-case: snake
      context: scope
      forbidden-keys:
        - time
        - level
        - msg

    gocritic:
      enable-all: true
      disabled-checks:
        - unnamedResult
        - singleCaseSwitch
      settings:
        hugeParam:
          sizeThreshold: 256

    godot:
      scope: all
      period: true
      capital: true

    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - io/ioutil.ReadFile
        - io.Copy(*bytes.Buffer)
        - io.Copy(os.Stdout)
        - os.Remove
        - os.RemoveAll

    grouper:
      const-require-grouping: true
      import-require-single-import: true
      var-require-single-var: true

    revive:
      enable-all-rules: true
      rules:
        - name: line-length-limit
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: add-constant
          disabled: true
        - name: function-length
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: nested-structs
          exclude:
            - "**/*_test.go"
        - name: package-comments
          exclude:
            - "**/examples/**"
        # Needed for future use.
        - name: unused-receiver
          disabled: true
        # Fails on private functions.
        - name: flag-parameter
          disabled: true
        # Requires named results.
        - name: confusing-results
          disabled: true
        - name: unnecessary-stmt
          disabled: true
        # Does not work with inline tags.
        - name: struct-tag
          disabled: true
        - name: var-naming
          disabled: true
        # Requires default cases.
        - name: enforce-switch-style
          disabled: true

    depguard:
      rules:
        main:
          deny:
            - pkg: "golang.org/x/exp/slog"
              desc: use log/slog
            - pkg: "github.com/pkg/errors"
              desc: use errors

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - dupl
          - promlinter
          - goconst
          - gosec
          - gosmopolitan
          - prealloc
      - path: _test\.go
        text: "fieldalignment:"
      - source: "= `"
        linters:
          - grouper
      - text: "\\*github\\.com/hashicorp/go-multierror\\.Error"
        linters:
          - wrapcheck
      - text: "\\*github\\.com/macropower/niceyaml\\.Source"
        linters:
          - wrapcheck
      - path: cmd/
        linters:
          - wrapcheck
      - path: internal/
        linters:
          - wrapcheck
      - path: examples/
        text: "printf"
        linters:
          - govet
      - path: style/theme/
        linters:
          - dupl
