package theme

import "go.jacobcolvin.com/niceyaml/style"

// catalog holds every built-in theme except charm, keyed by name.
//
// Most entries are derived from the Chroma syntax highlighter:
// https://github.com/alecthomas/chroma
var catalog = map[string]palette{
	"abap": {
		Mode:   Light,
		Fg:     "#000000",
		Bg:     "#ffffff",
		Accent: "#0000ff",
		OK:     "#22863a",
		Warn:   "#b07d2b",
		Error:  "#cb2431",
		Tokens: map[style.Kind]string{
			style.Comment:       "italic #888888",
			style.GenericError:  "#ff0000",
			style.LiteralNumber: "#33aaff",
			style.LiteralString: "#55aa22",
			style.Name:          "#000000",
			style.NameTag:       "#0000ff",
			style.Punctuation:   "#0000ff",
		},
	},
	"algol": {
		Mode:   Light,
		Fg:     "#000000",
		Bg:     "#ffffff",
		Accent: "#000000",
		OK:     "#22863a",
		Warn:   "#b07d2b",
		Error:  "#cb2431",
		Tokens: map[style.Kind]string{
			style.Comment:            "italic #888888",
			style.LiteralString:      "italic #666666",
			style.Name:               "bold italic",
			style.NameDecorator:      "bold #888888",
			style.NameTag:            "bold underline",
			style.Punctuation:        "bold",
			style.PunctuationHeading: "bold italic #666666",
		},
	},
	"algol-nu": {
		Mode:   Light,
		Fg:     "#000000",
		Bg:     "#ffffff",
		Accent: "#000000",
		OK:     "#22863a",
		Warn:   "#b07d2b",
		Error:  "#cb2431",
		Tokens: map[style.Kind]string{
			style.Comment:            "italic #888888",
			style.LiteralString:      "italic #666666",
			style.Name:               "bold italic",
			style.NameDecorator:      "bold #888888",
			style.NameTag:            "bold",
			style.Punctuation:        "bold",
			style.PunctuationHeading: "bold italic #666666",
		},
	},
	"arduino": {
		Mode:   Light,
		Fg:     "#000000",
		Bg:     "#ffffff",
		Accent: "#728e00",
		OK:     "#22863a",
		Warn:   "#d08700",
		Error:  "#cb2431",
		Tokens: map[style.Kind]string{
			style.Comment:        "#95a5a6",
			style.GenericError:   "#a61717",
			style.LiteralBoolean: "#00979d",
			style.LiteralNumber:  "#8a7b52",
			style.LiteralString:  "#7f8c8d",
			style.Name:           "#434f54",
			style.NameDecorator:  "#728e00",
			style.NameTag:        "#728e00",
			style.Punctuation:    "#728e00",
		},
	},
	"ashen": {
		Mode:   Dark,
		Fg:     "#b4b4b4",
		Bg:     "#121212",
		Accent: "#d87c4a",
		OK:     "#b4b4b4",
		Warn:   "#e8b57e",
		Error:  "#c53030",
		Tokens: map[style.Kind]string{
			style.Comment:            "italic #737373",
			style.Generic:            "#b4b4b4",
			style.GenericDeleted:     "#c53030",
			style.GenericError:       "#c53030",
			style.GenericInserted:    "bold #b4b4b4",
			style.LiteralBoolean:     "#4a8b8b",
			style.LiteralNumber:      "#4a8b8b",
			style.LiteralString:      "#df6464",
			style.Name:               "#b4b4b4",
			style.NameDecorator:      "bold italic #b4b4b4",
			style.NameTag:            "italic #d87c4a",
			style.Punctuation:        "#d5d5d5",
			style.PunctuationHeading: "bold #d87c4a",
		},
	},
	"aura-theme-dark": {
		Mode:   Dark,
		Fg:     "#edecee",
		Bg:     "#15141b",
		Accent: "#a277ff",
		OK:     "#61ffca",
		Warn:   "#ffca85",
		Error:  "#ff6767",
		Tokens: map[style.Kind]string{
			style.Comment:            "italic #6d6d6d",
			style.CommentPreproc:     "italic #6d6d6d",
			style.Generic:            "#edecee",
			style.GenericDeleted:     "#ff6767 bg:#15141b",
			style.GenericError:       "#ff6767",
			style.GenericInserted:    "#61ffca bg:#15141b",
			style.LiteralBoolean:     "#61ffca",
			style.LiteralNumber:      "#61ffca",
			style.LiteralString:      "#61ffca",
			style.Name:               "#edecee",
			style.NameDecorator:      "#f694ff",
			style.NameTag:            "#a277ff",
			style.Punctuation:        "#f694ff",
			style.PunctuationHeading: "#edecee",
		},
	},
	"aura-theme-dark-soft": {
		Mode:   Dark,
		Fg:     "#bdbdbd",
		Bg:     "#15141b",
		Accent: "#8464c6",
		OK:     "#54c59f",
		Warn:   "#ffca85",
		Error:  "#c55858",
		Tokens: map[style.Kind]string{
			style.Comment:            "italic #6d6d6d",
			style.CommentPreproc:     "italic #6d6d6d",
			style.Generic:            "#bdbdbd",
			style.GenericDeleted:     "#c55858 bg:#15141b",
			style.GenericError:       "#c55858",
			style.GenericInserted:    "#54c59f bg:#15141b",
			style.LiteralBoolean:     "#54c59f",
			style.LiteralNumber:      "#54c59f",
			style.LiteralString:      "#54c59f",
			style.Name:               "#bdbdbd",
			style.NameDecorator:      "#c17ac8",
			style.NameTag:            "#8464c6",
			style.Punctuation:        "#c17ac8",
			style.PunctuationHeading: "#bdbdbd",
		},
	},
	"autumn": {
		Mode:   Light,
		Fg:     "#000000",
		Bg:     "#ffffff",
		Accent: "#1e90ff",
		OK:     "#00aa00",
		Warn:   "#aa5500",
		Error:  "#aa0000",
		Tokens: map[style.Kind]string{
			style.Comment:            "italic #aaaaaa",
			style.Generic:            "italic",
			style.GenericDeleted:     "#aa0000",
			style.GenericError:       "#aa0000",
			style.GenericInserted:    "#00aa00",
			style.LiteralNumber:      "#009999",
			style.LiteralString:      "#aa5500",
			style.Name:               "#00aaaa",
			style.NameDecorator:      "#888888",
			style.NameTag:            "bold #1e90ff",
			style.Punctuation:        "#0000aa",
			style.PunctuationHeading: "underline #00aaaa",
		},
	},
	"average": {
		Mode:   Dark,
		Fg:     "#757575",
		Bg:     "#000000",
		Accent: "#ec0000",
		OK:     "#5faf5f",
		Warn:   "#e5c07b",
		Error:  "#ec0000",
		Tokens: map[style.Kind]string{
			style.Comment:            "#757575",
			style.Generic:            "#757575",
			style.GenericDeleted:     "#ec0000",
			style.GenericError:       "#ec0000",
			style.GenericInserted:    "bold #757575",
			style.LiteralBoolean:     "#ec0000",
			style.LiteralNumber:      "#008900",
			style.LiteralString:      "#008900",
			style.Name:               "#757575",
			style.NameDecorator:      "#008900",
			style.NameTag:            "#ec0000",
			style.Punctuation:        "#757575",
			style.PunctuationHeading: "#757575",
		},
	},
	"base16-snazzy": {
		Mode:   Dark,
		Fg:     "#e2e4e5",
		Bg:     "#282a36",
		Accent: "#ff6ac1",
		OK:     "#5af78e",
		Warn:   "#f3f99d",
		Error:  "#ff5c57",
		Tokens: map[style.Kind]string{
			style.Comment:            "#78787e",
			style.Generic:            "#e2e4e5",
			style.GenericDeleted:     "#ff5c57",
			style.GenericError:       "#ff5c57",
			style.GenericInserted:    "bold #e2e4e5",
			style.LiteralBoolean:     "#ff6ac1",
			style.LiteralNumber:      "#ff9f43",
			style.LiteralString:      "#5af78e",
			style.Name:               "#e2e4e5",
			style.NameDecorator:      "#ff9f43",
			style.NameTag:            "#ff6ac1",
			style.Punctuation:        "#e2e4e5",
			style.PunctuationHeading: "#e2e4e5",
		},
	},
	"borland": {
		Mode:   Light,
		Fg:     "#000000",
		Bg:     "#ffffff",
		Accent: "#000080",
		OK:     "#22863a",
		Warn:   "#d08700",
		Error:  "#cb2431",
		Tokens: map[style.Kind]string{
			style.Comment:         "italic #008800",
			style.Generic:         "italic",
			style.GenericDeleted:  "#000000 bg:#ffdddd",
			style.GenericError:    "#aa0000",
			style.GenericInserted: "#000000 bg:#ddffdd",
			style.LiteralNumber:   "#0000ff",
			style.LiteralString:   "#0000ff",
			style.NameDecorator:   "#008080",
			style.NameTag:         "bold #000080",
			style.Punctuation:     "bold",
		},
	},
	"bw": {
		Mode:   Light,
		Fg:     "#000000",
		Bg:     "#ffffff",
		Accent: "#000000",
		OK:     "#22863a",
		Warn:   "#b07d2b",
		Error:  "#cb2431",
		Tokens: map[style.Kind]string{
			style.Comment:            "italic",
			style.Generic:            "italic",
			style.LiteralString:      "italic",
			style.Name:               "bold",
			style.NameTag:            "bold",
			style.Punctuation:        "bold",
			style.PunctuationHeading: "bold",
		},
	},
	"catppuccin-frappe": {
		Mode:   Dark,
		Fg:     "#c6d0f5",
		Bg:     "#303446",
		Accent: "#ca9ee6",
		OK:     "#a6d189",
		Warn:   "#e5c890",
		Error:  "#e78284",
		Tokens: map[style.Kind]string{
			style.Comment:            "italic #737994",
			style.CommentPreproc:     "bold #737994",
			style.Generic:            "#c6d0f5",
			style.GenericDeleted:     "#e78284 bg:#414559",
			style.GenericError:       "#e78284",
			style.GenericInserted:    "#a6d189 bg:#414559",
			style.LiteralBoolean:     "#ef9f76",
			style.LiteralNumber:      "#ef9f76",
			style.LiteralString:      "#a6d189",
			style.Name:               "#c6d0f5",
			style.NameDecorator:      "bold #8caaee",
			style.NameTag:            "#ca9ee6",
			style.Punctuation:        "bold #99d1db",
			style.PunctuationHeading: "#ef9f76",
		},
	},
	"catppuccin-latte": {
		Mode:   Light,
		Fg:     "#4c4f69",
		Bg:     "#eff1f5",
		Accent: "#8839ef",
		OK:     "#40a02b",
		Warn:   "#df8e1d",
		Error:  "#d20f39",
		Tokens: map[style.Kind]string{
			style.Comment:            "italic #9ca0b0",
			style.CommentPreproc:     "bold #9ca0b0",
			style.Generic:            "#4c4f69",
			style.GenericDeleted:     "#d20f39 bg:#ccd0da",
			style.GenericError:       "#d20f39",
			style.GenericInserted:    "#40a02b bg:#ccd0da",
			style.LiteralBoolean:     "#fe640b",
			style.LiteralNumber:      "#fe640b",
			style.LiteralString:      "#40a02b",
			style.Name:               "#4c4f69",
			style.NameDecorator:      "bold #1e66f5",
			style.NameTag:            "#8839ef",
			style.Punctuation:        "bold #04a5e5",
			style.PunctuationHeading: "#fe640b",
		},
	},
	"catppuccin-macchiato": {
		Mode:   Dark,
		Fg:     "#cad3f5",
		Bg:     "#24273a",
		Accent: "#c6a0f6",
		OK:     "#a6da95",
		Warn:   "#eed49f",
		Error:  "#ed8796",
		Tokens: map[style.Kind]string{
			style.Comment:            "italic #6e738d",
			style.CommentPreproc:     "bold #6e738d",
			style.Generic:            "#cad3f5",
			style.GenericDeleted:     "#ed8796 bg:#363a4f",
			style.GenericError:       "#ed8796",
			style.GenericInserted:    "#a6da95 bg:#363a4f",
			style.LiteralBoolean:     "#f5a97f",
			style.LiteralNumber:      "#f5a97f",
			style.LiteralString:      "#a6da95",
			style.Name:               "#cad3f5",
			style.NameDecorator:      "bold #8aadf4",
			style.NameTag:            "#c6a0f6",
			style.Punctuation:        "bold #91d7e3",
			style.PunctuationHeading: "#f5a97f",
		},
	},
	"catppuccin-mocha": {
		Mode:   Dark,
		Fg:     "#cdd6f4",
		Bg:     "#1e1e2e",
		Accent: "#cba6f7",
		OK:     "#a6e3a1",
		Warn:   "#f9e2af",
		Error:  "#f38ba8",
		Tokens: map[style.Kind]string{
			style.Comment:            "italic #6c7086",
			style.CommentPreproc:     "bold #6c7086",
			style.Generic:            "#cdd6f4",
			style.GenericDeleted:     "#f38ba8 bg:#313244",
			style.GenericError:       "#f38ba8",
			style.GenericInserted:    "#a6e3a1 bg:#313244",
			style.LiteralBoolean:     "#fab387",
			style.LiteralNumber:      "#fab387",
			style.LiteralString:      "#a6e3a1",
			style.Name:               "#cdd6f4",
			style.NameDecorator:      "bold #89b4fa",
			style.NameTag:            "#cba6f7",
			style.Punctuation:        "bold #89dceb",
			style.PunctuationHeading: "#fab387",
		},
	},
	"colorful": {
		Mode:   Light,
		Fg:     "#000000",
		Bg:     "#ffffff",
		Accent: "#007700",
		OK:     "#00a000",
		Warn:   "#b07d2b",
		Error:  "#a00000",
		Tokens: map[style.Kind]string{
			style.Comment:              "#888888",
			style.Generic:              "italic",
			style.GenericDeleted:       "#a00000",
			style.GenericError:         "#ff0000",
			style.GenericInserted:      "#00a000",
			style.LiteralNumber:        "bold #6600ee",
			style.LiteralNumberHex:     "bold #005588",
			style.LiteralNumberInteger: "bold #0000dd",
			style.LiteralNumberOct:     "bold #4400ee",
			style.LiteralString:        "bg:#fff0f0",
			style.Name:                 "#007020",
			style.NameDecorator:        "bold #555555",
			style.NameTag:              "#007700",
			style.Punctuation:          "#333333",
			style.PunctuationHeading:   "bold #0e84b5",
		},
	},
	"doom-one": {
		Mode:   Dark,
		Fg:     "#b0c4de",
		Bg:     "#282c34",
		Accent: "#e06c75",
		OK:     "#a6e22e",
		Warn:   "#ecbe7b",
		Error:  "#ff5555",
		Tokens: map[style.Kind]string{
			style.Comment:             "italic #8a93a5",
			style.Generic:             "#b0c4de",
			style.GenericError:        "#b0c4de",
			style.GenericInserted:     "#a6e22e",
			style.LiteralBoolean:      "bold #b756ff",
			style.LiteralNumber:       "#d19a66",
			style.LiteralString:       "#98c379",
			style.LiteralStringDouble: "#63c381",
			style.Name:                "#c1abea",
			style.NameDecorator:       "#e5c07b",
			style.NameTag:             "#e06c75",
			style.Punctuation:         "#b0c4de",
			style.PunctuationHeading:  "#76a9f9",
		},
	},
	"doom-one2": {
		Mode:   Dark,
		Fg:     "#b0c4de",
		Bg:     "#282c34",
		Accent: "#76a9f9",
		OK:     "#a6e22e",
		Warn:   "#ecbe7b",
		Error:  "#ff6c6b",
		Tokens: map[style.Kind]string{
			style.Comment:             "italic #8a93a5",
			style.Generic:             "#b0c4de",
			style.GenericDeleted:      "#b0c4de",
			style.GenericError:        "#b0c4de",
			style.GenericInserted:     "#a6e22e",
			style.LiteralBoolean:      "#e5c07b",
			style.LiteralNumber:       "#d19a66",
			style.LiteralString:       "#98c379",
			style.LiteralStringDouble: "#63c381",
			style.Name:                "#aa89ea",
			style.NameDecorator:       "#e5c07b",
			style.NameTag:             "#76a9f9",
			style.Punctuation:         "#abb2bf",
			style.PunctuationHeading:  "#ca72ff",
		},
	},
	"dracula": {
		Mode:   Dark,
		Fg:     "#f8f8f2",
		Bg:     "#282a36",
		Accent: "#ff79c6",
		OK:     "#50fa7b",
		Warn:   "#f1fa8c",
		Error:  "#ff5555",
		Tokens: map[style.Kind]string{
			style.Comment:            "#6272a4",
			style.Generic:            "#f8f8f2",
			style.GenericDeleted:     "#ff5555",
			style.GenericError:       "#f8f8f2",
			style.GenericInserted:    "bold #50fa7b",
			style.LiteralBoolean:     "#ff79c6",
			style.LiteralNumber:      "#bd93f9",
			style.LiteralString:      "#f1fa8c",
			style.Name:               "#f8f8f2",
			style.NameDecorator:      "#f8f8f2",
			style.NameTag:            "#ff79c6",
			style.Punctuation:        "#f8f8f2",
			style.PunctuationHeading: "#f8f8f2",
		},
	},
	"emacs": {
		Mode:   Light,
		Fg:     "#000000",
		Bg:     "#f8f8f8",
		Accent: "#008000",
		OK:     "#00a000",
		Warn:   "#b07d2b",
		Error:  "#a00000",
		Tokens: map[style.Kind]string{
			style.Comment:            "italic #008800",
			style.Generic:            "italic",
			style.GenericDeleted:     "#a00000",
			style.GenericError:       "#ff0000",
			style.GenericInserted:    "#00a000",
			style.LiteralNumber:      "#666666",
			style.LiteralString:      "#bb4444",
			style.Name:               "#aa22ff",
			style.NameDecorator:      "#aa22ff",
			style.NameTag:            "bold #008000",
			style.Punctuation:        "#666666",
			style.PunctuationHeading: "bold #0000ff",
		},
	},
	"evergarden": {
		Mode:   Dark,
		Fg:     "#d6cbb4",
		Bg:     "#252b2e",
		Accent: "#7a8478",
		OK:     "#b2c98f",
		Warn:   "#e6b99d",
		Error:  "#e67e80",
		Tokens: map[style.Kind]string{
			style.Comment:         "italic #859289",
			style.Generic:         "#d6cbb4",
			style.GenericDeleted:  "#252b2e bg:#e67e80",
			style.GenericError:    "bold bg:#e67e80",
			style.GenericInserted: "#252b2e bg:#b2c98f",
			style.LiteralNumber:   "#d699b6",
			style.LiteralString:   "#b2c98f",
			style.Name:            "#d6cbb4",
			style.NameDecorator:   "#e67e80",
			style.NameTag:         "#7a8478",
			style.Punctuation:     "#7a8478",
		},
	},
	"friendly": {
		Mode:   Light,
		Fg:     "#000000",
		Bg:     "#f0f0f0",
		Accent: "#062873",
		OK:     "#00a000",
		Warn:   "#b07d2b",
		Error:  "#a00000",
		Tokens: map[style.Kind]string{
			style.Comment:            "italic #60a0b0",
			style.Generic:            "italic",
			style.GenericDeleted:     "#a00000",
			style.GenericError:       "#ff0000",
			style.GenericInserted:    "#00a000",
			style.LiteralNumber:      "#40a070",
			style.LiteralString:      "#4070a0",
			style.Name:               "#007020",
			style.NameDecorator:      "bold #555555",
			style.NameTag:            "bold #062873",
			style.Punctuation:        "#666666",
			style.PunctuationHeading: "bold #0e84b5",
		},
	},
	"fruity": {
		Mode:   Dark,
		Fg:     "#ffffff",
		Bg:     "#111111",
		Accent: "#fb660a",
		OK:     "#00ff00",
		Warn:   "#ffb86c",
		Error:  "#ff0000",
		Tokens: map[style.Kind]string{
			style.Comment:       "italic #008800 bg:#0f140f",
			style.Generic:       "bold #ffffff",
			style.LiteralNumber: "bold #0086f7",
			style.LiteralString: "#0086d2",
			style.Name:          "#0086d2",
			style.NameDecorator: "bold #ff0007",
			style.NameTag:       "bold #fb660a",
		},
	},
	"github": {
		Mode:   Light,
		Fg:     "#1f2328",
		Bg:     "#f7f7f7",
		Accent: "#0550ae",
		OK:     "#116329",
		Warn:   "#d08700",
		Error:  "#82071e",
		Tokens: map[style.Kind]string{
			style.Comment:         "#57606a",
			style.CommentPreproc:  "#57606a",
			style.GenericDeleted:  "#82071e bg:#ffebe9",
			style.GenericInserted: "#116329 bg:#dafbe1",
			style.LiteralNumber:   "#0550ae",
			style.LiteralString:   "#0a3069",
			style.NameDecorator:   "#0550ae",
			style.NameTag:         "#0550ae",
			style.Punctuation:     "#1f2328",
		},
	},
	"github-dark": {
		Mode:   Dark,
		Fg:     "#e6edf3",
		Bg:     "#0d1117",
		Accent: "#7ee787",
		OK:     "#56d364",
		Warn:   "#d29922",
		Error:  "#ffa198",
		Tokens: map[style.Kind]string{
			style.Comment:            "italic #8b949e",
			style.Generic:            "#e6edf3",
			style.GenericDeleted:     "#ffa198 bg:#490202",
			style.GenericError:       "#ffa198",
			style.GenericInserted:    "#56d364 bg:#0f5323",
			style.LiteralBoolean:     "#79c0ff",
			style.LiteralString:      "#a5d6ff",
			style.Name:               "#e6edf3",
			style.NameDecorator:      "bold #d2a8ff",
			style.NameTag:            "#7ee787",
			style.Punctuation:        "bold #ff7b72",
			style.PunctuationHeading: "#ff7b72",
		},
	},
	"gruvbox": {
		Mode:   Dark,
		Fg:     "#ebdbb2",
		Bg:     "#282828",
		Accent: "#fb4934",
		OK:     "#b8bb26",
		Warn:   "#fabd2f",
		Error:  "#fb4934",
		Tokens: map[style.Kind]string{
			style.Comment:         "italic #928374",
			style.Generic:         "#ebdbb2",
			style.GenericDeleted:  "#282828 bg:#fb4934",
			style.GenericError:    "bold bg:#fb4934",
			style.GenericInserted: "#282828 bg:#b8bb26",
			style.LiteralNumber:   "#d3869b",
			style.LiteralString:   "#b8bb26",
			style.Name:            "#ebdbb2",
			style.NameDecorator:   "#8ec07c",
			style.NameTag:         "#fb4934",
			style.Punctuation:     "#fe8019",
		},
	},
	"gruvbox-light": {
		Mode:   Light,
		Fg:     "#3c3836",
		Bg:     "#fbf1c7",
		Accent: "#9d0006",
		OK:     "#79740e",
		Warn:   "#b57614",
		Error:  "#9d0006",
		Tokens: map[style.Kind]string{
			style.Comment:         "italic #928374",
			style.Generic:         "#3c3836",
			style.GenericDeleted:  "#282828 bg:#9d0006",
			style.GenericError:    "bold bg:#9d0006",
			style.GenericInserted: "#282828 bg:#79740e",
			style.LiteralNumber:   "#8f3f71",
			style.LiteralString:   "#79740e",
			style.Name:            "#3c3836",
			style.NameDecorator:   "#427b58",
			style.NameTag:         "#9d0006",
			style.Punctuation:     "#af3a03",
		},
	},
	"hr-high-contrast": {
		Mode:   Dark,
		Fg:     "#d5d500",
		Bg:     "#000000",
		Accent: "#467faf",
		OK:     "#00ff00",
		Warn:   "#e5c07b",
		Error:  "#ff0000",
		Tokens: map[style.Kind]string{
			style.Comment:        "#5a8349",
			style.LiteralBoolean: "#467faf",
			style.LiteralNumber:  "#ffffff",
			style.LiteralString:  "#a87662",
			style.Name:           "#ffffff",
			style.NameTag:        "#467faf",
			style.Punctuation:    "#e4e400",
		},
	},
	"hrdark": {
		Mode:   Dark,
		Fg:     "#ffffff",
		Bg:     "#1d2432",
		Accent: "#ff636f",
		OK:     "#00ff00",
		Warn:   "#e5c07b",
		Error:  "#ff0000",
		Tokens: map[style.Kind]string{
			style.Comment:       "italic #828b96",
			style.LiteralString: "#a6be9d",
			style.Name:          "#58a1dd",
			style.NameTag:       "#ff636f",
			style.Punctuation:   "#ff636f",
		},
	},
	"igor": {
		Mode:   Light,
		Fg:     "#000000",
		Bg:     "#ffffff",
		Accent: "#0000ff",
		OK:     "#22863a",
		Warn:   "#d08700",
		Error:  "#cb2431",
		Tokens: map[style.Kind]string{
			style.Comment:       "italic #ff0000",
			style.LiteralString: "#009c00",
			style.Name:          "#007575",
			style.NameDecorator: "#cc00a3",
			style.NameTag:       "#0000ff",
		},
	},
	"kanagawa-dragon": {
		Mode:   Dark,
		Fg:     "#c5c9c5",
		Bg:     "#181616",
		Accent: "#8ba4b0",
		OK:     "#76946a",
		Warn:   "#e6c384",
		Error:  "#c34043",
		Tokens: map[style.Kind]string{
			style.Comment:         "italic #737c73",
			style.CommentPreproc:  "italic #c4746e",
			style.GenericDeleted:  "#c34043 bg:#43242b",
			style.GenericError:    "#e82424",
			style.GenericInserted: "#76946a bg:#2b3328",
			style.LiteralNumber:   "#a292a3",
			style.LiteralString:   "#8a9a7b",
			style.NameDecorator:   "bold #b6927b",
			style.NameTag:         "#8ba4b0",
			style.Punctuation:     "#c5c9c5",
		},
	},
	"kanagawa-lotus": {
		Mode:   Light,
		Fg:     "#545464",
		Bg:     "#f2ecbc",
		Accent: "#4d699b",
		OK:     "#6e915f",
		Warn:   "#cc6d00",
		Error:  "#d7474b",
		Tokens: map[style.Kind]string{
			style.Comment:         "italic #8a8980",
			style.CommentPreproc:  "italic #c84053",
			style.GenericDeleted:  "#d7474b bg:#d9a594",
			style.GenericError:    "#e82424",
			style.GenericInserted: "#6e915f bg:#b7d0ae",
			style.LiteralNumber:   "#b35b79",
			style.LiteralString:   "#6f894e",
			style.NameDecorator:   "bold #cc6d00",
			style.NameTag:         "#4d699b",
			style.Punctuation:     "#545464",
		},
	},
	"kanagawa-wave": {
		Mode:   Dark,
		Fg:     "#dcd7ba",
		Bg:     "#1f1f28",
		Accent: "#7e9cd8",
		OK:     "#76946a",
		Warn:   "#e6c384",
		Error:  "#c34043",
		Tokens: map[style.Kind]string{
			style.Comment:         "italic #727169",
			style.CommentPreproc:  "italic #e46876",
			style.GenericDeleted:  "#c34043 bg:#43242b",
			style.GenericError:    "#e82424",
			style.GenericInserted: "#76946a bg:#2b3328",
			style.LiteralNumber:   "#d27e99",
			style.LiteralString:   "#98bb6c",
			style.NameDecorator:   "bold #ffa066",
			style.NameTag:         "#7e9cd8",
			style.Punctuation:     "#dcd7ba",
		},
	},
	"lovelace": {
		Mode:   Light,
		Fg:     "#000000",
		Bg:     "#ffffff",
		Accent: "#2838b0",
		OK:     "#388038",
		Warn:   "#b07d2b",
		Error:  "#c02828",
		Tokens: map[style.Kind]string{
			style.Comment:            "italic #888888",
			style.Generic:            "italic",
			style.GenericDeleted:     "#c02828",
			style.GenericError:       "#c02828",
			style.GenericInserted:    "#388038",
			style.LiteralBoolean:     "italic #444444",
			style.LiteralNumber:      "#444444",
			style.LiteralString:      "#b83838",
			style.Name:               "#388038",
			style.NameDecorator:      "#287088",
			style.NameTag:            "#2838b0",
			style.Punctuation:        "#888888",
			style.PunctuationHeading: "#289870",
		},
	},
	"manni": {
		Mode:   Light,
		Fg:     "#000000",
		Bg:     "#f0f3f3",
		Accent: "#330099",
		OK:     "#22863a",
		Warn:   "#b07d2b",
		Error:  "#cb2431",
		Tokens: map[style.Kind]string{
			style.Comment:            "italic #0099ff",
			style.Generic:            "italic",
			style.GenericDeleted:     "bg:#ffcccc",
			style.GenericError:       "#ff0000",
			style.GenericInserted:    "bg:#ccffcc",
			style.LiteralNumber:      "#ff6600",
			style.LiteralString:      "#cc3300",
			style.Name:               "#336666",
			style.NameDecorator:      "#9999ff",
			style.NameTag:            "bold #330099",
			style.Punctuation:        "#555555",
			style.PunctuationHeading: "bold #00ccff",
		},
	},
	"modus-operandi": {
		Mode:   Light,
		Fg:     "#000000",
		Bg:     "#ffffff",
		Accent: "#5317ac",
		OK:     "#006800",
		Warn:   "#c65614",
		Error:  "#a60000",
		Tokens: map[style.Kind]string{
			style.Comment:        "#505050",
			style.LiteralBoolean: "#0000c0",
			style.LiteralString:  "#2544bb",
			style.Name:           "#8f0075",
			style.NameTag:        "#5317ac",
			style.Punctuation:    "#00538b",
		},
	},
	"modus-vivendi": {
		Mode:   Dark,
		Fg:     "#ffffff",
		Bg:     "#000000",
		Accent: "#b6a0ff",
		OK:     "#44bc44",
		Warn:   "#d0bc00",
		Error:  "#ff5f59",
		Tokens: map[style.Kind]string{
			style.Comment:        "#a8a8a8",
			style.LiteralBoolean: "#00bcff",
			style.LiteralString:  "#79a8ff",
			style.Name:           "#f78fe7",
			style.NameTag:        "#b6a0ff",
			style.Punctuation:    "#00d3d0",
		},
	},
	"monokai": {
		Mode:   Dark,
		Fg:     "#f8f8f2",
		Bg:     "#272822",
		Accent: "#f92672",
		OK:     "#a6e22e",
		Warn:   "#e6db74",
		Error:  "#f92672",
		Tokens: map[style.Kind]string{
			style.Comment:         "#75715e",
			style.Generic:         "italic",
			style.GenericDeleted:  "#f92672",
			style.GenericError:    "#960050 bg:#1e0010",
			style.GenericInserted: "#a6e22e",
			style.LiteralNumber:   "#ae81ff",
			style.LiteralString:   "#e6db74",
			style.Name:            "#f8f8f2",
			style.NameDecorator:   "#a6e22e",
			style.NameTag:         "#f92672",
			style.Punctuation:     "#f8f8f2",
		},
	},
	"monokailight": {
		Mode:   Light,
		Fg:     "#272822",
		Bg:     "#fafafa",
		Accent: "#f92672",
		OK:     "#22863a",
		Warn:   "#b07d2b",
		Error:  "#cb2431",
		Tokens: map[style.Kind]string{
			style.Comment:       "#75715e",
			style.Generic:       "italic",
			style.GenericError:  "#960050 bg:#1e0010",
			style.LiteralNumber: "#ae81ff",
			style.LiteralString: "#d88200",
			style.Name:          "#111111",
			style.NameDecorator: "#75af00",
			style.NameTag:       "#f92672",
			style.Punctuation:   "#111111",
		},
	},
	"murphy": {
		Mode:   Light,
		Fg:     "#000000",
		Bg:     "#ffffff",
		Accent: "#007700",
		OK:     "#00a000",
		Warn:   "#d08700",
		Error:  "#a00000",
		Tokens: map[style.Kind]string{
			style.Comment:              "italic #666666",
			style.Generic:              "italic",
			style.GenericDeleted:       "#a00000",
			style.GenericError:         "#ff0000",
			style.GenericInserted:      "#00a000",
			style.LiteralNumber:        "bold #6600ee",
			style.LiteralNumberHex:     "bold #005588",
			style.LiteralNumberInteger: "bold #6666ff",
			style.LiteralNumberOct:     "bold #4400ee",
			style.LiteralString:        "bg:#e0e0ff",
			style.Name:                 "#007722",
			style.NameDecorator:        "bold #555555",
			style.NameTag:              "#007700",
			style.Punctuation:          "#333333",
			style.PunctuationHeading:   "bold #0e84b5",
		},
	},
	"native": {
		Mode:   Dark,
		Fg:     "#d0d0d0",
		Bg:     "#202020",
		Accent: "#6ab825",
		OK:     "#589819",
		Warn:   "#ffb86c",
		Error:  "#d22323",
		Tokens: map[style.Kind]string{
			style.Comment:            "italic #999999",
			style.Generic:            "italic",
			style.GenericDeleted:     "#d22323",
			style.GenericError:       "#d22323",
			style.GenericInserted:    "#589819",
			style.LiteralNumber:      "#3677a9",
			style.LiteralString:      "#ed9d13",
			style.Name:               "#24909d",
			style.NameDecorator:      "#ffa500",
			style.NameTag:            "bold #6ab825",
			style.Punctuation:        "bold #6ab825",
			style.PunctuationHeading: "#447fcf",
		},
	},
	"nord": {
		Mode:   Dark,
		Fg:     "#d8dee9",
		Bg:     "#2e3440",
		Accent: "#81a1c1",
		OK:     "#a3be8c",
		Warn:   "#ebcb8b",
		Error:  "#bf616a",
		Tokens: map[style.Kind]string{
			style.Comment:            "italic #616e87",
			style.Generic:            "italic",
			style.GenericDeleted:     "#bf616a",
			style.GenericError:       "#bf616a",
			style.GenericInserted:    "#a3be8c",
			style.LiteralNumber:      "#b48ead",
			style.LiteralString:      "#a3be8c",
			style.Name:               "#d8dee9",
			style.NameDecorator:      "#d08770",
			style.NameTag:            "#81a1c1",
			style.Punctuation:        "#eceff4",
			style.PunctuationHeading: "#8fbcbb",
		},
	},
	"nordic": {
		Mode:   Dark,
		Fg:     "#bbc3d4",
		Bg:     "#242933",
		Accent: "#5e81ac",
		OK:     "#a3be8c",
		Warn:   "#ebcb8b",
		Error:  "#c5727a",
		Tokens: map[style.Kind]string{
			style.Comment:            "italic #4c566a",
			style.Generic:            "italic",
			style.GenericDeleted:     "#c5727a",
			style.GenericError:       "#c5727a",
			style.GenericInserted:    "#a3be8c",
			style.LiteralNumber:      "#b48ead",
			style.LiteralString:      "#a3be8c",
			style.Name:               "#bbc3d4",
			style.NameDecorator:      "#d08770",
			style.NameTag:            "#5e81ac",
			style.Punctuation:        "#eceff4",
			style.PunctuationHeading: "#8fbcbb",
		},
	},
	"onedark": {
		Mode:   Dark,
		Fg:     "#abb2bf",
		Bg:     "#282c34",
		Accent: "#e06c75",
		OK:     "#98c379",
		Warn:   "#e5c07b",
		Error:  "#e06c75",
		Tokens: map[style.Kind]string{
			style.Comment:         "#7f848e",
			style.GenericDeleted:  "#e06c75",
			style.GenericInserted: "bold #98c379",
			style.LiteralBoolean:  "#e5c07b",
			style.LiteralNumber:   "#d19a66",
			style.LiteralString:   "#98c379",
			style.Name:            "#e06c75",
			style.NameDecorator:   "#61afef",
			style.NameTag:         "#e06c75",
			style.Punctuation:     "#abb2bf",
		},
	},
	"onesenterprise": {
		Mode:   Light,
		Fg:     "#000000",
		Accent: "#ff0000",
		OK:     "#22863a",
		Warn:   "#986801",
		Error:  "#cb2431",
		Tokens: map[style.Kind]string{
			style.Comment:       "#008000",
			style.LiteralString: "#000000",
			style.Name:          "#0000ff",
			style.NameDecorator: "#963200",
			style.NameTag:       "#ff0000",
			style.Punctuation:   "#ff0000",
		},
		Overrides: []style.StylesOption{
			style.Set(style.GenericHeading, style.MustParse("bold bg:#ff0000")),
		},
	},
	"paraiso-dark": {
		Mode:   Dark,
		Fg:     "#e7e9db",
		Bg:     "#2f1e2e",
		Accent: "#5bc4bf",
		OK:     "#48b685",
		Warn:   "#f99b15",
		Error:  "#ef6155",
		Tokens: map[style.Kind]string{
			style.Comment:            "#776e71",
			style.Generic:            "italic",
			style.GenericDeleted:     "#ef6155",
			style.GenericError:       "#ef6155",
			style.GenericInserted:    "#48b685",
			style.LiteralNumber:      "#f99b15",
			style.LiteralString:      "#48b685",
			style.Name:               "#e7e9db",
			style.NameDecorator:      "#5bc4bf",
			style.NameTag:            "#5bc4bf",
			style.Punctuation:        "#e7e9db",
			style.PunctuationHeading: "#fec418",
		},
	},
	"paraiso-light": {
		Mode:   Light,
		Fg:     "#2f1e2e",
		Bg:     "#e7e9db",
		Accent: "#5bc4bf",
		OK:     "#48b685",
		Warn:   "#f99b15",
		Error:  "#ef6155",
		Tokens: map[style.Kind]string{
			style.Comment:            "#8d8687",
			style.Generic:            "italic",
			style.GenericDeleted:     "#ef6155",
			style.GenericError:       "#ef6155",
			style.GenericInserted:    "#48b685",
			style.LiteralNumber:      "#f99b15",
			style.LiteralString:      "#48b685",
			style.Name:               "#2f1e2e",
			style.NameDecorator:      "#5bc4bf",
			style.NameTag:            "#5bc4bf",
			style.Punctuation:        "#2f1e2e",
			style.PunctuationHeading: "#fec418",
		},
	},
	"pastie": {
		Mode:   Light,
		Fg:     "#000000",
		Bg:     "#ffffff",
		Accent: "#bb0066",
		OK:     "#22863a",
		Warn:   "#d08700",
		Error:  "#cb2431",
		Tokens: map[style.Kind]string{
			style.Comment:            "#888888",
			style.Generic:            "italic",
			style.GenericDeleted:     "#000000 bg:#ffdddd",
			style.GenericError:       "#aa0000",
			style.GenericInserted:    "#000000 bg:#ddffdd",
			style.LiteralNumber:      "bold #0000dd",
			style.LiteralString:      "#dd2200 bg:#fff0f0",
			style.Name:               "#003388",
			style.NameDecorator:      "#555555",
			style.NameTag:            "bold #bb0066",
			style.Punctuation:        "#008800",
			style.PunctuationHeading: "bold #bb0066",
		},
	},
	"perldoc": {
		Mode:   Light,
		Fg:     "#000000",
		Bg:     "#eeeedd",
		Accent: "#8b008b",
		OK:     "#00aa00",
		Warn:   "#b07d2b",
		Error:  "#aa0000",
		Tokens: map[style.Kind]string{
			style.Comment:            "#228b22",
			style.Generic:            "italic",
			style.GenericDeleted:     "#aa0000",
			style.GenericError:       "#aa0000",
			style.GenericInserted:    "#00aa00",
			style.LiteralNumber:      "#b452cd",
			style.LiteralString:      "#cd5555",
			style.Name:               "#658b00",
			style.NameDecorator:      "#707a7c",
			style.NameTag:            "bold #8b008b",
			style.Punctuation:        "#8b008b",
			style.PunctuationHeading: "underline #008b45",
		},
	},
	"pygments": {
		Mode:   Light,
		Accent: "#008000",
		OK:     "#00a000",
		Warn:   "#b07d2b",
		Error:  "#a00000",
		Tokens: map[style.Kind]string{
			style.Comment:            "italic #408080",
			style.Generic:            "italic",
			style.GenericDeleted:     "#a00000",
			style.GenericError:       "#ff0000",
			style.GenericInserted:    "#00a000",
			style.LiteralNumber:      "#666666",
			style.LiteralString:      "#ba2121",
			style.Name:               "#008000",
			style.NameDecorator:      "#aa22ff",
			style.NameTag:            "bold #008000",
			style.Punctuation:        "#666666",
			style.PunctuationHeading: "bold #0000ff",
		},
		Overrides: []style.StylesOption{
			style.Set(style.GenericHeading, style.MustParse("bold bg:#008000")),
		},
	},
	"rainbow-dash": {
		Mode:   Light,
		Fg:     "#4d4d4d",
		Bg:     "#ffffff",
		Accent: "#2c5dcd",
		OK:     "#22863a",
		Warn:   "#d08700",
		Error:  "#cb2431",
		Tokens: map[style.Kind]string{
			style.Comment:         "italic #0080ff",
			style.Generic:         "italic",
			style.GenericDeleted:  "bg:#ffcccc",
			style.GenericError:    "#ff0000",
			style.GenericInserted: "bg:#ccffcc",
			style.LiteralNumber:   "bold #5918bb",
			style.LiteralString:   "#00cc66",
			style.Name:            "bold #5918bb",
			style.NameDecorator:   "bold #ff8000",
			style.NameTag:         "bold #2c5dcd",
			style.Punctuation:     "#2c5dcd",
		},
	},
	"rose-pine": {
		Mode:   Dark,
		Fg:     "#e0def4",
		Bg:     "#191724",
		Accent: "#ebbcba",
		OK:     "#9ccfd8",
		Warn:   "#f6c177",
		Error:  "#eb6f92",
		Tokens: map[style.Kind]string{
			style.Comment:         "#6e6a86",
			style.Generic:         "italic",
			style.GenericDeleted:  "#eb6f92",
			style.GenericError:    "#eb6f92",
			style.GenericInserted: "#9ccfd8",
			style.LiteralNumber:   "#f6c177",
			style.LiteralString:   "#f6c177",
			style.Name:            "#ebbcba",
			style.NameDecorator:   "#908caa",
			style.NameTag:         "#ebbcba",
			style.Punctuation:     "#908caa",
		},
	},
	"rose-pine-dawn": {
		Mode:   Light,
		Fg:     "#575279",
		Bg:     "#faf4ed",
		Accent: "#d7827e",
		OK:     "#56949f",
		Warn:   "#ea9d34",
		Error:  "#b4637a",
		Tokens: map[style.Kind]string{
			style.Comment:         "#9893a5",
			style.Generic:         "italic",
			style.GenericDeleted:  "#b4637a",
			style.GenericError:    "#b4637a",
			style.GenericInserted: "#56949f",
			style.LiteralNumber:   "#ea9d34",
			style.LiteralString:   "#ea9d34",
			style.Name:            "#d7827e",
			style.NameDecorator:   "#797593",
			style.NameTag:         "#d7827e",
			style.Punctuation:     "#797593",
		},
	},
	"rose-pine-moon": {
		Mode:   Dark,
		Fg:     "#e0def4",
		Bg:     "#232136",
		Accent: "#ea9a97",
		OK:     "#9ccfd8",
		Warn:   "#f6c177",
		Error:  "#eb6f92",
		Tokens: map[style.Kind]string{
			style.Comment:         "#6e6a86",
			style.Generic:         "italic",
			style.GenericDeleted:  "#eb6f92",
			style.GenericError:    "#eb6f92",
			style.GenericInserted: "#9ccfd8",
			style.LiteralNumber:   "#f6c177",
			style.LiteralString:   "#f6c177",
			style.Name:            "#ea9a97",
			style.NameDecorator:   "#908caa",
			style.NameTag:         "#ea9a97",
			style.Punctuation:     "#908caa",
		},
	},
	"rpgle": {
		Mode:   Light,
		Fg:     "#272822",
		Bg:     "#fafafa",
		Accent: "#f92672",
		OK:     "#22863a",
		Warn:   "#d08700",
		Error:  "#cb2431",
		Tokens: map[style.Kind]string{
			style.Comment:       "#75715e",
			style.Generic:       "italic",
			style.GenericError:  "#960050 bg:#1e0010",
			style.LiteralNumber: "#ae81ff",
			style.LiteralString: "#d88200",
			style.Name:          "#111111",
			style.NameDecorator: "#75af00",
			style.NameTag:       "#f92672",
			style.Punctuation:   "#ff0000",
		},
	},
	"rrt": {
		Mode:   Dark,
		Fg:     "#f8f8f2",
		Bg:     "#000000",
		Accent: "#ff0000",
		OK:     "#00ff00",
		Warn:   "#ffb86c",
		Error:  "#ff0000",
		Tokens: map[style.Kind]string{
			style.Comment:         "#00ff00",
			style.Generic:         "italic",
			style.GenericDeleted:  "#f00",
			style.GenericInserted: "#0f0",
			style.LiteralNumber:   "#ff6600",
			style.LiteralString:   "#87ceeb",
			style.Name:            "#7fffd4",
			style.NameDecorator:   "#e5e5e5",
			style.NameTag:         "#ff0000",
		},
	},
	"solarized-dark": {
		Mode:   Dark,
		Fg:     "#93a1a1",
		Bg:     "#002b36",
		Accent: "#268bd2",
		OK:     "#719e07",
		Warn:   "#b58900",
		Error:  "#dc322f",
		Tokens: map[style.Kind]string{
			style.Comment:         "#586e75",
			style.Generic:         "italic",
			style.GenericDeleted:  "#dc322f",
			style.GenericError:    "bold #dc322f",
			style.GenericInserted: "#719e07",
			style.LiteralBoolean:  "#cb4b16",
			style.LiteralNumber:   "#2aa198",
			style.LiteralString:   "#2aa198",
			style.Name:            "#b58900",
			style.NameDecorator:   "#268bd2",
			style.NameTag:         "#268bd2",
			style.Punctuation:     "#719e07",
		},
	},
	"solarized-dark256": {
		Mode:   Dark,
		Fg:     "#8a8a8a",
		Bg:     "#1c1c1c",
		Accent: "#0087ff",
		OK:     "#5f8700",
		Warn:   "#af8700",
		Error:  "#af0000",
		Tokens: map[style.Kind]string{
			style.Comment:         "#4e4e4e",
			style.Generic:         "italic",
			style.GenericDeleted:  "#af0000",
			style.GenericError:    "bold #af0000",
			style.GenericInserted: "#5f8700",
			style.LiteralBoolean:  "#d75f00",
			style.LiteralNumber:   "#00afaf",
			style.LiteralString:   "#00afaf",
			style.Name:            "#0087ff",
			style.NameDecorator:   "#0087ff",
			style.NameTag:         "#0087ff",
			style.Punctuation:     "#8a8a8a",
		},
	},
	"solarized-light": {
		Mode:   Light,
		Fg:     "#586e75",
		Bg:     "#eee8d5",
		Accent: "#586e75",
		OK:     "#719e07",
		Warn:   "#b58900",
		Error:  "#dc322f",
		Tokens: map[style.Kind]string{
			style.Comment:        "italic #93a1a1",
			style.Generic:        "#d33682",
			style.LiteralBoolean: "bold",
			style.LiteralNumber:  "bold",
			style.LiteralString:  "#2aa198",
			style.Name:           "#268bd2",
			style.NameTag:        "bold",
			style.Punctuation:    "#859900",
		},
	},
	"swapoff": {
		Mode:   Dark,
		Fg:     "#e5e5e5",
		Bg:     "#000000",
		Accent: "#e5e5e5",
		OK:     "#00ff00",
		Warn:   "#ffb86c",
		Error:  "#ff0000",
		Tokens: map[style.Kind]string{
			style.Comment:       "#007f7f",
			style.Generic:       "bold",
			style.GenericError:  "#ff0000",
			style.LiteralNumber: "bold #ffff00",
			style.LiteralString: "bold #00ffff",
			style.Name:          "bold #ffffff",
			style.NameDecorator: "bold #00ff00",
			style.NameTag:       "bold",
		},
	},
	"tango": {
		Mode:   Light,
		Fg:     "#000000",
		Bg:     "#f8f8f8",
		Accent: "#204a87",
		OK:     "#00a000",
		Warn:   "#c4a000",
		Error:  "#a40000",
		Tokens: map[style.Kind]string{
			style.Comment:            "italic #8f5902",
			style.Generic:            "#000000",
			style.GenericDeleted:     "#a40000",
			style.GenericError:       "#ef2929",
			style.GenericInserted:    "#00a000",
			style.LiteralBoolean:     "bold #204a87",
			style.LiteralNumber:      "bold #0000cf",
			style.LiteralString:      "#4e9a06",
			style.Name:               "#000000",
			style.NameDecorator:      "bold #5c35cc",
			style.NameTag:            "bold #204a87",
			style.Punctuation:        "bold #000000",
			style.PunctuationHeading: "#000000",
		},
	},
	"tokyonight-day": {
		Mode:   Light,
		Fg:     "#3760bf",
		Bg:     "#e1e2e7",
		Accent: "#9854f1",
		OK:     "#587539",
		Warn:   "#965027",
		Error:  "#c64343",
		Tokens: map[style.Kind]string{
			style.Comment:            "italic #a1a6c5",
			style.CommentPreproc:     "bold #a1a6c5",
			style.Generic:            "#3760bf",
			style.GenericDeleted:     "#c64343 bg:#e9e9ed",
			style.GenericError:       "#c64343",
			style.GenericInserted:    "#587539 bg:#e9e9ed",
			style.LiteralBoolean:     "#8c6c3e",
			style.LiteralNumber:      "#8c6c3e",
			style.LiteralString:      "#587539",
			style.Name:               "#3760bf",
			style.NameDecorator:      "bold #2e7de9",
			style.NameTag:            "#9854f1",
			style.Punctuation:        "bold #587539",
			style.PunctuationHeading: "#8c6c3e",
		},
	},
	"tokyonight-moon": {
		Mode:   Dark,
		Fg:     "#c8d3f5",
		Bg:     "#222436",
		Accent: "#c099ff",
		OK:     "#c3e88d",
		Warn:   "#ff9e64",
		Error:  "#c53b53",
		Tokens: map[style.Kind]string{
			style.Comment:            "italic #444a73",
			style.CommentPreproc:     "bold #444a73",
			style.Generic:            "#c8d3f5",
			style.GenericDeleted:     "#c53b53 bg:#1b1d2b",
			style.GenericError:       "#c53b53",
			style.GenericInserted:    "#c3e88d bg:#1b1d2b",
			style.LiteralBoolean:     "#ffc777",
			style.LiteralNumber:      "#ffc777",
			style.LiteralString:      "#c3e88d",
			style.Name:               "#c8d3f5",
			style.NameDecorator:      "bold #82aaff",
			style.NameTag:            "#c099ff",
			style.Punctuation:        "bold #c3e88d",
			style.PunctuationHeading: "#ffc777",
		},
	},
	"tokyonight-night": {
		Mode:   Dark,
		Fg:     "#c0caf5",
		Bg:     "#1a1b26",
		Accent: "#bb9af7",
		OK:     "#9ece6a",
		Warn:   "#e0af68",
		Error:  "#db4b4b",
		Tokens: map[style.Kind]string{
			style.Comment:            "italic #414868",
			style.CommentPreproc:     "bold #414868",
			style.Generic:            "#c0caf5",
			style.GenericDeleted:     "#db4b4b bg:#15161e",
			style.GenericError:       "#db4b4b",
			style.GenericInserted:    "#9ece6a bg:#15161e",
			style.LiteralBoolean:     "#e0af68",
			style.LiteralNumber:      "#e0af68",
			style.LiteralString:      "#9ece6a",
			style.Name:               "#c0caf5",
			style.NameDecorator:      "bold #7aa2f7",
			style.NameTag:            "#bb9af7",
			style.Punctuation:        "bold #9ece6a",
			style.PunctuationHeading: "#e0af68",
		},
	},
	"tokyonight-storm": {
		Mode:   Dark,
		Fg:     "#c0caf5",
		Bg:     "#1a1b26",
		Accent: "#bb9af7",
		OK:     "#9ece6a",
		Warn:   "#e0af68",
		Error:  "#db4b4b",
		Tokens: map[style.Kind]string{
			style.Comment:            "italic #414868",
			style.CommentPreproc:     "bold #414868",
			style.Generic:            "#c0caf5",
			style.GenericDeleted:     "#db4b4b bg:#15161e",
			style.GenericError:       "#db4b4b",
			style.GenericInserted:    "#9ece6a bg:#15161e",
			style.LiteralBoolean:     "#e0af68",
			style.LiteralNumber:      "#e0af68",
			style.LiteralString:      "#9ece6a",
			style.Name:               "#c0caf5",
			style.NameDecorator:      "bold #7aa2f7",
			style.NameTag:            "#bb9af7",
			style.Punctuation:        "bold #9ece6a",
			style.PunctuationHeading: "#e0af68",
		},
		Overrides: []style.StylesOption{
			style.Set(style.GenericHeadingOK, style.MustParse("bold #24283b bg:#9ece6a")),
			style.Set(style.GenericHeadingWarn, style.MustParse("bold #24283b bg:#e0af68")),
			style.Set(style.GenericHeadingError, style.MustParse("bold #24283b bg:#db4b4b")),
		},
	},
	"trac": {
		Mode:   Light,
		Fg:     "#000000",
		Bg:     "#ffffff",
		Accent: "#000080",
		OK:     "#22863a",
		Warn:   "#b07d2b",
		Error:  "#cb2431",
		Tokens: map[style.Kind]string{
			style.Comment:            "italic #999988",
			style.Generic:            "italic",
			style.GenericDeleted:     "#000000 bg:#ffdddd",
			style.GenericError:       "#aa0000",
			style.GenericInserted:    "#000000 bg:#ddffdd",
			style.LiteralNumber:      "#009999",
			style.LiteralString:      "#bb8844",
			style.Name:               "#999999",
			style.NameDecorator:      "bold #999999",
			style.NameTag:            "#000080",
			style.Punctuation:        "bold",
			style.PunctuationHeading: "#555555",
		},
	},
	"vim": {
		Mode:   Dark,
		Fg:     "#cccccc",
		Bg:     "#000000",
		Accent: "#cdcd00",
		OK:     "#00cd00",
		Warn:   "#cdcd00",
		Error:  "#cd0000",
		Tokens: map[style.Kind]string{
			style.Comment:         "#000080",
			style.Generic:         "italic",
			style.GenericDeleted:  "#cd0000",
			style.GenericError:    "#ff0000",
			style.GenericInserted: "#00cd00",
			style.LiteralNumber:   "#cd00cd",
			style.LiteralString:   "#cd0000",
			style.Name:            "#cd00cd",
			style.NameTag:         "#cdcd00",
			style.Punctuation:     "#3399cc",
		},
	},
	"vs": {
		Mode:   Light,
		Fg:     "#000000",
		Bg:     "#ffffff",
		Accent: "#0000ff",
		OK:     "#22863a",
		Warn:   "#d08700",
		Error:  "#cb2431",
		Tokens: map[style.Kind]string{
			style.Comment:       "#008000",
			style.Generic:       "italic",
			style.LiteralString: "#a31515",
			style.Name:          "#2b91af",
			style.NameDecorator: "#0000ff",
			style.NameTag:       "#0000ff",
			style.Punctuation:   "#0000ff",
		},
	},
	"vulcan": {
		Mode:   Dark,
		Fg:     "#c9c9c9",
		Bg:     "#282c34",
		Accent: "#bc74c4",
		OK:     "#ecbe7b",
		Warn:   "#ffb86c",
		Error:  "#cf5967",
		Tokens: map[style.Kind]string{
			style.Comment:            "#3e4460",
			style.Generic:            "#c9c9c9",
			style.GenericDeleted:     "#cf5967",
			style.GenericError:       "bold #cf5967",
			style.GenericInserted:    "#ecbe7b",
			style.LiteralBoolean:     "#cf5967 bg:#43454f",
			style.LiteralNumber:      "#56b6c2",
			style.LiteralNumberBin:   "#57c7ff",
			style.LiteralNumberHex:   "#57c7ff",
			style.LiteralNumberOct:   "#57c7ff",
			style.LiteralString:      "#82cc6a",
			style.Name:               "#c9c9c9",
			style.NameDecorator:      "#ecbe7b",
			style.NameTag:            "#bc74c4",
			style.Punctuation:        "#56b6c2",
			style.PunctuationHeading: "#c9c9c9",
		},
	},
	"witchhazel": {
		Mode:   Dark,
		Fg:     "#f8f8f2",
		Bg:     "#433e56",
		Accent: "#ffb8d1",
		OK:     "#a6e22e",
		Warn:   "#fff352",
		Error:  "#f92672",
		Tokens: map[style.Kind]string{
			style.Comment:         "#b0bec5",
			style.Generic:         "italic",
			style.GenericDeleted:  "#f92672",
			style.GenericError:    "#960050 bg:#1e0010",
			style.GenericInserted: "#a6e22e",
			style.LiteralNumber:   "#c5a3ff",
			style.LiteralString:   "#1bc5e0",
			style.Name:            "#f8f8f2",
			style.NameDecorator:   "#ceb1ff",
			style.NameTag:         "#ffb8d1",
			style.Punctuation:     "#f8f8f2",
		},
	},
	"xcode": {
		Mode:   Light,
		Fg:     "#000000",
		Bg:     "#ffffff",
		Accent: "#000000",
		OK:     "#22863a",
		Warn:   "#d08700",
		Error:  "#cb2431",
		Tokens: map[style.Kind]string{
			style.Comment:       "#177500",
			style.GenericError:  "#000000",
			style.LiteralNumber: "#1c01ce",
			style.LiteralString: "#c41a16",
			style.Name:          "#000000",
			style.NameDecorator: "#000000",
			style.NameTag:       "#000000",
			style.Punctuation:   "#000000",
		},
	},
	"xcode-dark": {
		Mode:   Dark,
		Fg:     "#ffffff",
		Bg:     "#1f1f24",
		Accent: "#fc5fa3",
		OK:     "#4eb400",
		Warn:   "#d0a946",
		Error:  "#ff0000",
		Tokens: map[style.Kind]string{
			style.Comment:        "#6c7986",
			style.GenericError:   "#960050",
			style.LiteralBoolean: "#fc5fa3",
			style.LiteralNumber:  "#d0bf69",
			style.LiteralString:  "#fc6a5d",
			style.Name:           "#ffffff",
			style.NameDecorator:  "#fd8f3f",
			style.NameTag:        "#fc5fa3",
			style.Punctuation:    "#ffffff",
		},
	},
}
