Output docs/assets/revisions.gif

Set Theme "OneDark"
Set Shell "bash"
Set Padding 20
Set FontSize 22
Set Width 1420
Set Height 800

Hide
  Type `go build -o dist/nyaml ./cmd/nyaml`  Enter
  Type `alias nyaml=./dist/nyaml`  Enter
  Type `nyaml view testdata/revisions/*.yaml` Enter
  Sleep 500ms
Show

# Can't loop over control+key commands :(
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms
Shift+Tab Sleep 25ms

Sleep 1

Tab@50ms 100

Sleep 1
